### ISSUE TITLE
Consider the use of a unit testing framework

### ISSUE THREAD

**Issue by thierryseegers** [bouzinabdotcom/CCommentator#3]
Unit testing frameworks allow on to easily describe all the tests and special cases that our program should pass and they produce a nice report of which tests passed or failed when done. In professional development environments, testing and unit testing are unavoidable.

Popular testing frameworks I'm familiar with are [GTest](https://github.com/google/googletest/blob/master/googletest/docs/primer.md) and [Catch2](https://github.com/catchorg/Catch2/blob/devel/docs/tutorial.md#top). For this project, I'd be partial towards Catch2 as I think it would be the simplest to integrate. (Note that these two frameworks are *C++* frameworks but adapting the codebase to it should be fairly straightforward.)

When unit testing, write tests that are as short as possible and test a single case. Best to have multiple tests for small cases than a big test for everything.

Consider writing unit tests that invoke `removeCode` (which has been refactored to only do parsing as suggested in #1 ) and use `open_memstream` to pass in short strings wrapped in `FILE` stream as test cases.

**Comment by bouzinabdotcom** [comment]
Using `open_memstream` is problematic with `removeCode`. It appears that the `FILE` created by it can't be passed to `ftell` which is a crucial dependency (in that case it keeps returning -1 an error value). I might just emulate `open_memstream` with a custom function and use that. 
Also, I noticed the same problem when I tried to fix #2 : if the user doesn't pass a file as stdin and types instead into the prompt the result is corrupted and `ftell(stdin) ==> -1`

**Comment by bouzinabdotcom** [comment]
Oh! unless I use a counter of type `long` (`fseek`'s argument type) that holds the position of the cursor instead of using `ftell()` that'll solve the observed issue while fixing #2 as well.

**Comment by bouzinabdotcom** [comment]
> Oh! unless I use a counter of type `long` (`fseek`'s argument type) that holds the position of the cursor instead of using `ftell()` that'll solve the observed issue while fixing #2 as well.

Not a chance! The problem is that the [fifos are unseekable](https://stackoverflow.com/questions/2502489/why-ftell-stdin-causes-illegal-seek-error).

**Comment by bouzinabdotcom** [comment]
One way to fix it might be to write a function that converts a buffer to a temporary physical file like this:

``` c
void buffer_to_file(FILE * buffer, char * tmpfilename) {
    FILE * tmpfile = fopen(tmpfilename, "w");
    char c;
    if(tmpfile != NULL) {
        while((c = fgetc(buffer)) != EOF) {
            fputc(c, tmpfile);
        }
        fclose(tmpfile);
    }else{
        puts("error: can\'t open file.");
        exit(EXIT_FAILURE);
    }
}
```

It fixed the issue with stdin (of course the file gets deleted after removing the code and the filename is random to avoid conflict) . but using this function in test s might be a bad idea. I'm still looking for a way to automate the different steps done before and after each test in Catch2 if there's a way it would practical otherwise a before and after functions will be written to reduce the amount of boilerplate code that'll get repeated.

**Comment by bouzinabdotcom** [comment]
So I've basically used ` buffer_to_file` in a `before` function that does all the required config and call to `removeCode` before testing the assertion as follows:

``` c
void before(const char* teststr) {
    input = open_memstream(&istr, &ilen);
    output = open_memstream(&ostr, &olen);

    fprintf(input, "%s", teststr);
    buffer_to_file(input, "tmp");
    removeCode(open_iofile("tmp", 0), output);
    remove("tmp"); //we don't need it after removeCode
    fflush(input);
    fflush(output);
}
```

and an `after` function to clean everything up: 

``` c
void after() {
    istr = NULL;
    ostr = NULL;
    fclose(input);
    fclose(output);
}
```

Then used them before and after the assertion:

``` c
TEST_CASE("leave inline comments", "[removecode]") {
    before("//test\n");

    REQUIRE(strcmp(istr, ostr) == 0);

    after();
    
}
```
